[tool.poetry]
name = "Annotations"
version = "0.1.0"
description = ""
authors = ["AnastasAlexandrovich <a-khoroshilova@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mypy = "^1.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
